In [17]:
import pandas as pd

In [18]:
df = pd.read_csv('./player_stats.csv')

stats_df = df.copy()
stats_df = stats_df[stats_df["season"] != "2024-25"]

for c in stats_df.columns:
    try:
        stats_df[c] = pd.to_numeric(stats_df[c])
    except :
        pass

stats_df

,Rk,player_url,season,Player,Age,Team,Pos,G,GS,MP,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Trp-Dbl,Awards
0,1,https://www.basketball-reference.com/players/h...,2019-20,James Harden,30,HOU,SG,68,68,2483,...,376,446,512,125,60,308,227,2335,4,"MVP-3,AS,NBA1"
1,2,https://www.basketball-reference.com/players/l...,2019-20,Damian Lillard,29,POR,PG,66,66,2474,...,251,284,530,70,22,194,114,1978,1,"MVP-8,AS,NBA2"
2,3,https://www.basketball-reference.com/players/b...,2019-20,Devin Booker,23,PHO,SG,70,70,2512,...,268,297,456,49,18,264,213,1863,0,AS
3,4,https://www.basketball-reference.com/players/a...,2019-20,Giannis Antetokounmpo,25,MIL,PF,63,63,1917,...,716,856,354,61,66,230,195,1857,4,"MVP-1,DPOY-1,AS,NBA1,DEF1"
4,5,https://www.basketball-reference.com/players/y...,2019-20,Trae Young,21,ATL,PG,60,60,2120,...,223,255,560,65,8,289,104,1778,2,AS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3577,568,https://www.basketball-reference.com/players/g...,2023-24,Danny Green,36,PHI,SG,2,0,18,...,2,2,1,1,0,0,1,0,0,NaN
3578,569,https://www.basketball-reference.com/players/h...,2023-24,Ron Harper Jr.,23,TOR,PF,1,0,4,...,0,0,1,0,0,0,2,0,0,NaN
3579,570,https://www.basketball-reference.com/players/j...,2023-24,Justin Jackson,28,MIN,SF,2,0,1,...,0,0,0,0,0,0,0,0,0,NaN
3580,571,https://www.basketball-reference.com/players/s...,2023-24,Dmytro Skapintsev,25,NYK,C,2,0,2,...,0,0,0,0,0,0,0,0,0,NaN
3581,572,https://www.basketball-reference.com/players/s...,2023-24,Javonte Smart,24,PHI,PG,1,0,1,...,0,0,0,0,0,0,0,0,0,NaN

In [19]:
df_copy = stats_df[stats_df['Awards'].notna() & (~stats_df['Team'].str.match(r'^\d+TM$'))]

awards_df = df_copy[['season', 'Player', 'Team', 'Awards']].copy()
awards_df['Awards'] = awards_df['Awards'].str.split(',')
awards_df = awards_df.explode('Awards')

awards_df

       season              Player Team  Awards
0     2019-20        James Harden  HOU   MVP-3
0     2019-20        James Harden  HOU      AS
0     2019-20        James Harden  HOU    NBA1
1     2019-20      Damian Lillard  POR   MVP-8
1     2019-20      Damian Lillard  POR      AS
...       ...                 ...  ...     ...
3033  2023-24         Alex Caruso  CHI    DEF2
3044  2023-24  Brandin Podziemski  GSW   ROY-5
3121  2023-24    Dereck Lively II  DAL   ROY-6
3150  2023-24       Jose Alvarado  NOP  6MOY-6
3151  2023-24      Jonathan Isaac  ORL  6MOY-9

[488 rows x 4 columns]

In [20]:
def seperate_mvp_rank(awards):
    items = str(awards).split(',')
    for item in items:
        if item.startswith('MVP-'):
            return int(item.split('MVP-')[1])
    return 0

stats_df['mvp_rank'] = stats_df['Awards'].apply(seperate_mvp_rank)

stats_df.drop(columns='Awards', inplace=True)

stats_df

,Rk,player_url,season,Player,Age,Team,Pos,G,GS,MP,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Trp-Dbl,mvp_rank
0,1,https://www.basketball-reference.com/players/h...,2019-20,James Harden,30,HOU,SG,68,68,2483,...,376,446,512,125,60,308,227,2335,4,3
1,2,https://www.basketball-reference.com/players/l...,2019-20,Damian Lillard,29,POR,PG,66,66,2474,...,251,284,530,70,22,194,114,1978,1,8
2,3,https://www.basketball-reference.com/players/b...,2019-20,Devin Booker,23,PHO,SG,70,70,2512,...,268,297,456,49,18,264,213,1863,0,0
3,4,https://www.basketball-reference.com/players/a...,2019-20,Giannis Antetokounmpo,25,MIL,PF,63,63,1917,...,716,856,354,61,66,230,195,1857,4,1
4,5,https://www.basketball-reference.com/players/y...,2019-20,Trae Young,21,ATL,PG,60,60,2120,...,223,255,560,65,8,289,104,1778,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3577,568,https://www.basketball-reference.com/players/g...,2023-24,Danny Green,36,PHI,SG,2,0,18,...,2,2,1,1,0,0,1,0,0,0
3578,569,https://www.basketball-reference.com/players/h...,2023-24,Ron Harper Jr.,23,TOR,PF,1,0,4,...,0,0,1,0,0,0,2,0,0,0
3579,570,https://www.basketball-reference.com/players/j...,2023-24,Justin Jackson,28,MIN,SF,2,0,1,...,0,0,0,0,0,0,0,0,0,0
3580,571,https://www.basketball-reference.com/players/s...,2023-24,Dmytro Skapintsev,25,NYK,C,2,0,2,...,0,0,0,0,0,0,0,0,0,0
3581,572,https://www.basketball-reference.com/players/s...,2023-24,Javonte Smart,24,PHI,PG,1,0,1,...,0,0,0,0,0,0,0,0,0,0

In [21]:
total_nulls = stats_df.isna().sum().sum()
print(f'Total NULL: {total_nulls}\n')

nulls = stats_df.isna().sum()
print(f'Null in each column:\n{nulls[nulls > 0]}\n')

Total NULL: 587

Null in each column:
FG%      30
3P%     212
2P%      60
eFG%     30
FT%     255
dtype: int64

In [22]:
stats_df = stats_df.fillna(0)

stats_df.isna().sum().sum()

0

In [23]:
stats_df

,Rk,player_url,season,Player,Age,Team,Pos,G,GS,MP,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Trp-Dbl,mvp_rank
0,1,https://www.basketball-reference.com/players/h...,2019-20,James Harden,30,HOU,SG,68,68,2483,...,376,446,512,125,60,308,227,2335,4,3
1,2,https://www.basketball-reference.com/players/l...,2019-20,Damian Lillard,29,POR,PG,66,66,2474,...,251,284,530,70,22,194,114,1978,1,8
2,3,https://www.basketball-reference.com/players/b...,2019-20,Devin Booker,23,PHO,SG,70,70,2512,...,268,297,456,49,18,264,213,1863,0,0
3,4,https://www.basketball-reference.com/players/a...,2019-20,Giannis Antetokounmpo,25,MIL,PF,63,63,1917,...,716,856,354,61,66,230,195,1857,4,1
4,5,https://www.basketball-reference.com/players/y...,2019-20,Trae Young,21,ATL,PG,60,60,2120,...,223,255,560,65,8,289,104,1778,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3577,568,https://www.basketball-reference.com/players/g...,2023-24,Danny Green,36,PHI,SG,2,0,18,...,2,2,1,1,0,0,1,0,0,0
3578,569,https://www.basketball-reference.com/players/h...,2023-24,Ron Harper Jr.,23,TOR,PF,1,0,4,...,0,0,1,0,0,0,2,0,0,0
3579,570,https://www.basketball-reference.com/players/j...,2023-24,Justin Jackson,28,MIN,SF,2,0,1,...,0,0,0,0,0,0,0,0,0,0
3580,571,https://www.basketball-reference.com/players/s...,2023-24,Dmytro Skapintsev,25,NYK,C,2,0,2,...,0,0,0,0,0,0,0,0,0,0
3581,572,https://www.basketball-reference.com/players/s...,2023-24,Javonte Smart,24,PHI,PG,1,0,1,...,0,0,0,0,0,0,0,0,0,0

In [24]:
headers = {
    'Rk': 'rank',
    'season': 'season_name',
    'Player': 'player_name',
    'Age': 'age',
    'Team': 'team_name_abbr',
    'Pos': 'position',
    'G': 'games',
    'GS': 'games_started',
    'MP': 'minutes_played',
    'FG': 'field_goals_made',
    'FGA': 'field_goals_attempted',
    'FG%': 'field_goals_percent',
    '3P': 'three_point',
    '3PA': 'three_point_attempted',
    '3P%': 'three_point_percent',
    '2P': 'two_point',
    '2PA': 'two_point_attempted',
    '2P%': 'two_point_percent',
    'eFG%': 'effective_field_goal_percent',
    'FT': 'field_throws_made',
    'FTA': 'field_throws_made_attempted',
    'FT%': 'field_throws_made_percent',
    'ORB': 'offensive_rebound',
    'DRB': 'defensive_rebound',
    'TRB': 'total_rebound',
    'AST': 'assists',
    'STL': 'steals',
    'BLK': 'blocks',
    'TOV': 'turnovers',
    'PF': 'personal_fouls',
    'PTS': 'points',
    'Trp-Dbl': 'triple_double',
    'mvp_rank': 'mvp_awards'
}

stats_df = stats_df.rename(columns=headers)
stats_df

,rank,player_url,season_name,player_name,age,team_name_abbr,position,games,games_started,minutes_played,...,defensive_rebound,total_rebound,assists,steals,blocks,turnovers,personal_fouls,points,triple_double,mvp_awards
0,1,https://www.basketball-reference.com/players/h...,2019-20,James Harden,30,HOU,SG,68,68,2483,...,376,446,512,125,60,308,227,2335,4,3
1,2,https://www.basketball-reference.com/players/l...,2019-20,Damian Lillard,29,POR,PG,66,66,2474,...,251,284,530,70,22,194,114,1978,1,8
2,3,https://www.basketball-reference.com/players/b...,2019-20,Devin Booker,23,PHO,SG,70,70,2512,...,268,297,456,49,18,264,213,1863,0,0
3,4,https://www.basketball-reference.com/players/a...,2019-20,Giannis Antetokounmpo,25,MIL,PF,63,63,1917,...,716,856,354,61,66,230,195,1857,4,1
4,5,https://www.basketball-reference.com/players/y...,2019-20,Trae Young,21,ATL,PG,60,60,2120,...,223,255,560,65,8,289,104,1778,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3577,568,https://www.basketball-reference.com/players/g...,2023-24,Danny Green,36,PHI,SG,2,0,18,...,2,2,1,1,0,0,1,0,0,0
3578,569,https://www.basketball-reference.com/players/h...,2023-24,Ron Harper Jr.,23,TOR,PF,1,0,4,...,0,0,1,0,0,0,2,0,0,0
3579,570,https://www.basketball-reference.com/players/j...,2023-24,Justin Jackson,28,MIN,SF,2,0,1,...,0,0,0,0,0,0,0,0,0,0
3580,571,https://www.basketball-reference.com/players/s...,2023-24,Dmytro Skapintsev,25,NYK,C,2,0,2,...,0,0,0,0,0,0,0,0,0,0
3581,572,https://www.basketball-reference.com/players/s...,2023-24,Javonte Smart,24,PHI,PG,1,0,1,...,0,0,0,0,0,0,0,0,0,0

In [25]:
# prepare teams table

teams_name_df = pd.read_excel('player_stats.xlsx', sheet_name='teams_name')

teams_name_df.rename(columns={'full_name': 'team_name'}, inplace=True)

teams_name_df['id'] = range(1, len(teams_name_df) + 1)

with pd.ExcelWriter('player_stats.xlsx', engine='openpyxl', mode='a', if_sheet_exists='replace') as writer:
    teams_name_df.to_excel(writer, sheet_name='teams', index=False)

teams_name_df

                 team_name abbr_name  id
0            Atlanta Hawks       ATL   1
1           Boston Celtics       BOS   2
2            Brooklyn Nets       NJN   3
3        Charlotte Hornets       CHA   4
4            Chicago Bulls       CHI   5
5      Cleveland Cavaliers       CLE   6
6         Dallas Mavericks       DAL   7
7           Denver Nuggets       DEN   8
8          Detroit Pistons       DET   9
9    Golden State Warriors       GSW  10
10         Houston Rockets       HOU  11
11          Indiana Pacers       IND  12
12    Los Angeles Clippers       LAC  13
13      Los Angeles Lakers       LAL  14
14       Memphis Grizzlies       MEM  15
15              Miami Heat       MIA  16
16         Milwaukee Bucks       MIL  17
17  Minnesota Timberwolves       MIN  18
18    New Orleans Pelicans       NOH  19
19         New York Knicks       NYK  20
20   Oklahoma City Thunder       OKC  21
21           Orlando Magic       ORL  22
22      Philadelphia 76ers       PHI  23
23            Phoenix Suns       PHO  24
24  Portland Trail Blazers       POR  25
25        Sacramento Kings       SAC  26
26       San Antonio Spurs       SAS  27
27         Toronto Raptors       TOR  28
28               Utah Jazz       UTA  29
29      Washington Wizards       WAS  30
30    New Orleans Pelicans       NOP  31
31           Brooklyn Nets       BRK  32
32       Charlotte Hornets       CHO  33
33                     2TM       2TM  34
34                     3TM       3TM  35
35                     4TM       4TM  36

In [26]:
season_df = pd.read_excel('player_stats.xlsx', sheet_name='season')
position_df = pd.read_excel('player_stats.xlsx', sheet_name='position')

season_map = dict(zip(season_df['season_name'], season_df['id']))
position_map = dict(zip(position_df['position_name'], position_df['id']))
team_map = dict(zip(teams_name_df['team_name'], teams_name_df['id']))

In [27]:
team_abbr_to_full = dict(zip(teams_name_df['abbr_name'], teams_name_df['team_name']))
stats_df['team_name_abbr'] = stats_df['team_name_abbr'].map(team_abbr_to_full)

stats_df.rename(columns={'team_name_abbr': 'team_name'}, inplace=True)

with pd.ExcelWriter('player_stats.xlsx', engine='openpyxl', mode='a', if_sheet_exists='replace') as writer:
    stats_df.to_excel(writer, sheet_name='stats', index=False)
    # awards_df.to_excel(writer, sheet_name='awards', index=True)

In [28]:
def convert_season(season_year):
    separator = '_' if '_' in season_year else '-'
    first, second = season_year.split(separator)
    return f'{first}-{int(second)-2000}'

In [30]:
# prepare team_seasons table

team_seasons_df = pd.read_excel('Teams_Final.xlsx', sheet_name='Teams_Final')

team_seasons_df['season'] = team_seasons_df['season'].apply(convert_season)
team_seasons_df.drop(columns='team_link', inplace=True)

team_seasons_df['season'] = team_seasons_df['season'].map(season_map)
team_seasons_df.rename(columns={'season': 'season_id'}, inplace=True)

team_seasons_df['team_name'] = team_seasons_df['team_name'].map(team_map)
team_seasons_df.rename(columns={'team_name': 'team_id'}, inplace=True)

team_seasons_df['id'] = range(1, len(team_seasons_df) + 1)

with pd.ExcelWriter('player_stats.xlsx', engine='openpyxl', mode='a', if_sheet_exists='replace') as writer:
    team_seasons_df.to_excel(writer, sheet_name='team_seasons', index=False)

team_seasons_df

     season_id  team_id             coach                     arena   id
0            1        7     Rick Carlisle  American Airlines Center    1
1            1       17  Mike Budenholzer              Fiserv Forum    2
2            1       25      Terry Stotts               Moda Center    3
3            1       11     Mike D'Antoni             Toyota Center    4
4            1       13        Doc Rivers            STAPLES Center    5
..         ...      ...               ...                       ...  ...
145          5       16    Erik Spoelstra             Kaseya Center  146
146          5        9    Monty Williams      Little Caesars Arena  147
147          5       33    Steve Clifford           Spectrum Center  148
148          5       25  Chauncey Billups               Moda Center  149
149          5       15    Taylor Jenkins               FedEx Forum  150

[150 rows x 5 columns]

In [31]:
# prepare player table

roster = pd.read_excel('./Roster.xlsx') 
players_df = roster[['player_name', 'birth_country', 'birth_date', 'age', 'height_cm', 'weight_kg', 'college', 'agility']].drop_duplicates('player_name')
players_df['id'] = range(1, len(players_df) + 1)

# change country name

country_df = pd.read_excel('./player_stats.xlsx', sheet_name='countries')
country_map = dict(zip(country_df['player_name'], country_df['nationality']))

players_df["birth_country"] = players_df['player_name'].map(country_map)

with pd.ExcelWriter('player_stats.xlsx', engine='openpyxl', mode='a', if_sheet_exists='replace') as writer:
    players_df.to_excel(writer, sheet_name='players', index=False)

players_df

,player_name,birth_country,birth_date,age,height_cm,weight_kg,college,agility,id
0,J.J. Barea,Puerto Rico,1984-06-26,41,178,82,Northeastern University,2.17,1
1,Ryan Broekhoff,Australia,1990-08-23,35,198,98,Valparaiso,2.02,2
2,Jalen Brunson,United States,1996-08-31,29,188,86,Villanova,2.19,3
3,Trey Burke,United States,1992-11-12,33,183,84,Michigan,2.18,4
4,Willie Cauley-Stein,United States,1993-08-18,32,213,109,Kentucky,1.95,5
...,...,...,...,...,...,...,...,...,...
3162,Rayan Rupert,France,2004-05-31,21,201,93,NaN,2.16,959
3170,Timmy Allen,United States,2000-01-09,25,198,95,"Utah, Texas",2.08,960
3179,Matthew Hurt,United States,2000-04-20,25,206,106,Duke,1.94,961
3180,GG Jackson II,United States,2004-12-17,21,206,95,South Carolina,2.17,962
3190,Mãozinha Pereira,Brazil,2000-08-28,25,203,80,NaN,2.54,963

In [32]:
players_df = pd.read_excel('player_stats.xlsx', sheet_name='players')
players_map = dict(zip(players_df['player_name'], players_df['id']))

In [33]:
# prepare stats table

stats_df = pd.read_excel('player_stats.xlsx', sheet_name='stats')

# # add salary
# salary_df  = pd.read_csv('./salary.csv')

# salary_df['season_name'] = salary_df['season_name'].apply(convert_season)

# merge_salary = stats_df.merge(salary_df[['player_name', 'season_name', 'team_name', 'salary']], on=['player_name', 'season_name', 'team_name'], how='left')

# with pd.ExcelWriter('player_stats.xlsx', engine='openpyxl', mode='a', if_sheet_exists='replace') as writer:
#     merge_salary.to_excel(writer, sheet_name='check', index=False)
# merge_salary


# add experience

roster_df = pd.read_excel('Roster.xlsx', sheet_name='stats')
roster_df.rename(columns={'season': 'season_name'}, inplace=True)

roster_df['season_name'] = roster_df['season_name'].apply(convert_season)

merge_experience = stats_df.merge(roster_df[['player_name', 'season_name', 'team_name', 'experience']], on=['player_name', 'season_name', 'team_name'], how='left')

portable_players = merge_experience['team_name'].str.contains('TM', na=False)

first_team = merge_experience['team_name'].where(~portable_players).groupby([merge_experience['player_name'], merge_experience['season_name']]).transform('first')
merge_experience.loc[portable_players, 'team_name'] = first_team

merge_experience.loc[portable_players, 'experience'] = merge_experience.groupby(['player_name', 'season_name'])['experience'].transform('first')

merge_experience = merge_experience[~merge_experience.duplicated(['player_name', 'season_name'], keep='first')]

merge_experience['innate_ability'] = round(merge_experience['experience']/ merge_experience['age'],2)

merge_experience.drop('player_url', axis=1, inplace=True)

merge_experience['season_name'] = merge_experience['season_name'].map(season_map)
merge_experience['position'] = merge_experience['position'].map(position_map)
merge_experience['player_name'] = merge_experience['player_name'].map(players_map)
merge_experience['team_name'] = merge_experience['team_name'].map(team_map)

merge_experience['multi_team_flag'] = 0
merge_experience.loc[portable_players, 'multi_team_flag'] = 1

merge_experience.rename(columns={'season_name': 'season_id', 'position': 'position_id', 'player_name': 'player_id', 'team_name': 'team_id'}, inplace=True)

merge_experience['id'] = range(1, len(merge_experience) + 1)

with pd.ExcelWriter('player_stats.xlsx', engine='openpyxl', mode='a', if_sheet_exists='replace') as writer:
    merge_experience.to_excel(writer, sheet_name='stats', index=False)
merge_experience

,rank,season_id,player_id,age,team_id,position_id,games,games_started,minutes_played,field_goals_made,...,blocks,turnovers,personal_fouls,points,triple_double,mvp_awards,experience,innate_ability,multi_team_flag,id
0,1,1,68,30,11,1,68,68,2483,672,...,60,308,227,2335,4,3,10.0,0.33,0,1
1,2,1,48,29,25,2,66,66,2474,624,...,22,194,114,1978,1,8,7.0,0.24,0,2
2,3,1,118,23,24,1,70,70,2512,627,...,18,264,213,1863,0,0,4.0,0.17,0,3
3,4,1,20,25,17,3,63,63,1917,685,...,66,230,195,1857,4,1,6.0,0.24,0,4
4,5,1,427,21,1,2,60,60,2120,546,...,8,289,104,1778,2,0,1.0,0.05,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3577,568,5,290,36,23,1,2,0,18,0,...,0,0,1,0,0,0,14.0,0.39,0,2781
3578,569,5,841,23,28,3,1,0,4,0,...,0,0,2,0,0,0,1.0,0.04,0,2782
3579,570,5,11,28,18,4,2,0,1,0,...,0,0,0,0,0,0,6.0,0.21,0,2783
3580,571,5,920,25,20,5,2,0,2,0,...,0,0,0,0,0,0,0.0,0.00,0,2784
3581,572,5,648,24,23,2,1,0,1,0,...,0,0,0,0,0,0,1.0,0.04,0,2785